name: mlprojects
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - matplotlib=3.7.2
  - numpy=1.25.2
  - scikit-learn=1.3.0
  - pip=23.2.1
  - pip:
      - -r requirements.txt
